// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: emptypackage.proto

package emptypackage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmptyPackageServiceClient is the client API for EmptyPackageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptyPackageServiceClient interface {
	Unary(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type emptyPackageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptyPackageServiceClient(cc grpc.ClientConnInterface) EmptyPackageServiceClient {
	return &emptyPackageServiceClient{cc}
}

func (c *emptyPackageServiceClient) Unary(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/EmptyPackageService/Unary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyPackageServiceServer is the server API for EmptyPackageService service.
// All implementations must embed UnimplementedEmptyPackageServiceServer
// for forward compatibility
type EmptyPackageServiceServer interface {
	Unary(context.Context, *SimpleRequest) (*SimpleResponse, error)
	mustEmbedUnimplementedEmptyPackageServiceServer()
}

// UnimplementedEmptyPackageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmptyPackageServiceServer struct {
}

func (UnimplementedEmptyPackageServiceServer) Unary(context.Context, *SimpleRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedEmptyPackageServiceServer) mustEmbedUnimplementedEmptyPackageServiceServer() {}

// UnsafeEmptyPackageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptyPackageServiceServer will
// result in compilation errors.
type UnsafeEmptyPackageServiceServer interface {
	mustEmbedUnimplementedEmptyPackageServiceServer()
}

func RegisterEmptyPackageServiceServer(s grpc.ServiceRegistrar, srv EmptyPackageServiceServer) {
	s.RegisterService(&EmptyPackageService_ServiceDesc, srv)
}

func _EmptyPackageService_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyPackageServiceServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmptyPackageService/Unary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyPackageServiceServer).Unary(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmptyPackageService_ServiceDesc is the grpc.ServiceDesc for EmptyPackageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmptyPackageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmptyPackageService",
	HandlerType: (*EmptyPackageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _EmptyPackageService_Unary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emptypackage.proto",
}
