// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gender int32

const (
	Gender_Male   Gender = 0
	Gender_Female Gender = 1
)

var Gender_name = map[int32]string{
	0: "Male",
	1: "Female",
}
var Gender_value = map[string]int32{
	"Male":   0,
	"Female": 1,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{0}
}

type SimpleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRequest) Reset()         { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()    {}
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{0}
}
func (m *SimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRequest.Unmarshal(m, b)
}
func (m *SimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRequest.Marshal(b, m, deterministic)
}
func (dst *SimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRequest.Merge(dst, src)
}
func (m *SimpleRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleRequest.Size(m)
}
func (m *SimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRequest proto.InternalMessageInfo

func (m *SimpleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SimpleResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{1}
}
func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (dst *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(dst, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Name struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{2}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Name) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type UnaryMessageRequest struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryMessageRequest) Reset()         { *m = UnaryMessageRequest{} }
func (m *UnaryMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMessageRequest) ProtoMessage()    {}
func (*UnaryMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{3}
}
func (m *UnaryMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMessageRequest.Unmarshal(m, b)
}
func (m *UnaryMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMessageRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMessageRequest.Merge(dst, src)
}
func (m *UnaryMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMessageRequest.Size(m)
}
func (m *UnaryMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMessageRequest proto.InternalMessageInfo

func (m *UnaryMessageRequest) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type UnaryRepeatedRequest struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryRepeatedRequest) Reset()         { *m = UnaryRepeatedRequest{} }
func (m *UnaryRepeatedRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryRepeatedRequest) ProtoMessage()    {}
func (*UnaryRepeatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{4}
}
func (m *UnaryRepeatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryRepeatedRequest.Unmarshal(m, b)
}
func (m *UnaryRepeatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryRepeatedRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryRepeatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryRepeatedRequest.Merge(dst, src)
}
func (m *UnaryRepeatedRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryRepeatedRequest.Size(m)
}
func (m *UnaryRepeatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryRepeatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryRepeatedRequest proto.InternalMessageInfo

func (m *UnaryRepeatedRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type UnaryRepeatedMessageRequest struct {
	Name                 []*Name  `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryRepeatedMessageRequest) Reset()         { *m = UnaryRepeatedMessageRequest{} }
func (m *UnaryRepeatedMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryRepeatedMessageRequest) ProtoMessage()    {}
func (*UnaryRepeatedMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{5}
}
func (m *UnaryRepeatedMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryRepeatedMessageRequest.Unmarshal(m, b)
}
func (m *UnaryRepeatedMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryRepeatedMessageRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryRepeatedMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryRepeatedMessageRequest.Merge(dst, src)
}
func (m *UnaryRepeatedMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryRepeatedMessageRequest.Size(m)
}
func (m *UnaryRepeatedMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryRepeatedMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryRepeatedMessageRequest proto.InternalMessageInfo

func (m *UnaryRepeatedMessageRequest) GetName() []*Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type UnaryRepeatedEnumRequest struct {
	Genders              []Gender `protobuf:"varint,1,rep,packed,name=genders,proto3,enum=api.Gender" json:"genders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryRepeatedEnumRequest) Reset()         { *m = UnaryRepeatedEnumRequest{} }
func (m *UnaryRepeatedEnumRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryRepeatedEnumRequest) ProtoMessage()    {}
func (*UnaryRepeatedEnumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{6}
}
func (m *UnaryRepeatedEnumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryRepeatedEnumRequest.Unmarshal(m, b)
}
func (m *UnaryRepeatedEnumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryRepeatedEnumRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryRepeatedEnumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryRepeatedEnumRequest.Merge(dst, src)
}
func (m *UnaryRepeatedEnumRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryRepeatedEnumRequest.Size(m)
}
func (m *UnaryRepeatedEnumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryRepeatedEnumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryRepeatedEnumRequest proto.InternalMessageInfo

func (m *UnaryRepeatedEnumRequest) GetGenders() []Gender {
	if m != nil {
		return m.Genders
	}
	return nil
}

type UnarySelfRequest struct {
	You                  *Person  `protobuf:"bytes,1,opt,name=you,proto3" json:"you,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnarySelfRequest) Reset()         { *m = UnarySelfRequest{} }
func (m *UnarySelfRequest) String() string { return proto.CompactTextString(m) }
func (*UnarySelfRequest) ProtoMessage()    {}
func (*UnarySelfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{7}
}
func (m *UnarySelfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnarySelfRequest.Unmarshal(m, b)
}
func (m *UnarySelfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnarySelfRequest.Marshal(b, m, deterministic)
}
func (dst *UnarySelfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnarySelfRequest.Merge(dst, src)
}
func (m *UnarySelfRequest) XXX_Size() int {
	return xxx_messageInfo_UnarySelfRequest.Size(m)
}
func (m *UnarySelfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnarySelfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnarySelfRequest proto.InternalMessageInfo

func (m *UnarySelfRequest) GetYou() *Person {
	if m != nil {
		return m.You
	}
	return nil
}

type Person struct {
	Name                 *Name     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string    `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Friends              []*Person `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{8}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Person) GetFriends() []*Person {
	if m != nil {
		return m.Friends
	}
	return nil
}

type UnaryMapRequest struct {
	Kvs                  map[string]string `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UnaryMapRequest) Reset()         { *m = UnaryMapRequest{} }
func (m *UnaryMapRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMapRequest) ProtoMessage()    {}
func (*UnaryMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{9}
}
func (m *UnaryMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMapRequest.Unmarshal(m, b)
}
func (m *UnaryMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMapRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMapRequest.Merge(dst, src)
}
func (m *UnaryMapRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMapRequest.Size(m)
}
func (m *UnaryMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMapRequest proto.InternalMessageInfo

func (m *UnaryMapRequest) GetKvs() map[string]string {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type UnaryMapMessageRequest struct {
	Kvs                  map[string]*Name `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UnaryMapMessageRequest) Reset()         { *m = UnaryMapMessageRequest{} }
func (m *UnaryMapMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMapMessageRequest) ProtoMessage()    {}
func (*UnaryMapMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{10}
}
func (m *UnaryMapMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMapMessageRequest.Unmarshal(m, b)
}
func (m *UnaryMapMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMapMessageRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryMapMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMapMessageRequest.Merge(dst, src)
}
func (m *UnaryMapMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMapMessageRequest.Size(m)
}
func (m *UnaryMapMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMapMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMapMessageRequest proto.InternalMessageInfo

func (m *UnaryMapMessageRequest) GetKvs() map[string]*Name {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type UnaryOneofRequest struct {
	// Types that are valid to be assigned to Name:
	//	*UnaryOneofRequest_Msg
	//	*UnaryOneofRequest_Plain
	Name                 isUnaryOneofRequest_Name `protobuf_oneof:"name"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UnaryOneofRequest) Reset()         { *m = UnaryOneofRequest{} }
func (m *UnaryOneofRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryOneofRequest) ProtoMessage()    {}
func (*UnaryOneofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{11}
}
func (m *UnaryOneofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryOneofRequest.Unmarshal(m, b)
}
func (m *UnaryOneofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryOneofRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryOneofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryOneofRequest.Merge(dst, src)
}
func (m *UnaryOneofRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryOneofRequest.Size(m)
}
func (m *UnaryOneofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryOneofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryOneofRequest proto.InternalMessageInfo

type isUnaryOneofRequest_Name interface {
	isUnaryOneofRequest_Name()
}

type UnaryOneofRequest_Msg struct {
	Msg *Name `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

type UnaryOneofRequest_Plain struct {
	Plain string `protobuf:"bytes,2,opt,name=plain,proto3,oneof"`
}

func (*UnaryOneofRequest_Msg) isUnaryOneofRequest_Name() {}

func (*UnaryOneofRequest_Plain) isUnaryOneofRequest_Name() {}

func (m *UnaryOneofRequest) GetName() isUnaryOneofRequest_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UnaryOneofRequest) GetMsg() *Name {
	if x, ok := m.GetName().(*UnaryOneofRequest_Msg); ok {
		return x.Msg
	}
	return nil
}

func (m *UnaryOneofRequest) GetPlain() string {
	if x, ok := m.GetName().(*UnaryOneofRequest_Plain); ok {
		return x.Plain
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UnaryOneofRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UnaryOneofRequest_OneofMarshaler, _UnaryOneofRequest_OneofUnmarshaler, _UnaryOneofRequest_OneofSizer, []interface{}{
		(*UnaryOneofRequest_Msg)(nil),
		(*UnaryOneofRequest_Plain)(nil),
	}
}

func _UnaryOneofRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UnaryOneofRequest)
	// name
	switch x := m.Name.(type) {
	case *UnaryOneofRequest_Msg:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg); err != nil {
			return err
		}
	case *UnaryOneofRequest_Plain:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Plain)
	case nil:
	default:
		return fmt.Errorf("UnaryOneofRequest.Name has unexpected type %T", x)
	}
	return nil
}

func _UnaryOneofRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UnaryOneofRequest)
	switch tag {
	case 1: // name.msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Name)
		err := b.DecodeMessage(msg)
		m.Name = &UnaryOneofRequest_Msg{msg}
		return true, err
	case 2: // name.plain
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Name = &UnaryOneofRequest_Plain{x}
		return true, err
	default:
		return false, nil
	}
}

func _UnaryOneofRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UnaryOneofRequest)
	// name
	switch x := m.Name.(type) {
	case *UnaryOneofRequest_Msg:
		s := proto.Size(x.Msg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UnaryOneofRequest_Plain:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Plain)))
		n += len(x.Plain)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UnaryEnumRequest struct {
	Gender               Gender   `protobuf:"varint,1,opt,name=gender,proto3,enum=api.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryEnumRequest) Reset()         { *m = UnaryEnumRequest{} }
func (m *UnaryEnumRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryEnumRequest) ProtoMessage()    {}
func (*UnaryEnumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{12}
}
func (m *UnaryEnumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryEnumRequest.Unmarshal(m, b)
}
func (m *UnaryEnumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryEnumRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryEnumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryEnumRequest.Merge(dst, src)
}
func (m *UnaryEnumRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryEnumRequest.Size(m)
}
func (m *UnaryEnumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryEnumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryEnumRequest proto.InternalMessageInfo

func (m *UnaryEnumRequest) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_Male
}

type UnaryBytesRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryBytesRequest) Reset()         { *m = UnaryBytesRequest{} }
func (m *UnaryBytesRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryBytesRequest) ProtoMessage()    {}
func (*UnaryBytesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6027c29d237ac4bb, []int{13}
}
func (m *UnaryBytesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryBytesRequest.Unmarshal(m, b)
}
func (m *UnaryBytesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryBytesRequest.Marshal(b, m, deterministic)
}
func (dst *UnaryBytesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryBytesRequest.Merge(dst, src)
}
func (m *UnaryBytesRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryBytesRequest.Size(m)
}
func (m *UnaryBytesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryBytesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryBytesRequest proto.InternalMessageInfo

func (m *UnaryBytesRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleRequest)(nil), "api.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "api.SimpleResponse")
	proto.RegisterType((*Name)(nil), "api.Name")
	proto.RegisterType((*UnaryMessageRequest)(nil), "api.UnaryMessageRequest")
	proto.RegisterType((*UnaryRepeatedRequest)(nil), "api.UnaryRepeatedRequest")
	proto.RegisterType((*UnaryRepeatedMessageRequest)(nil), "api.UnaryRepeatedMessageRequest")
	proto.RegisterType((*UnaryRepeatedEnumRequest)(nil), "api.UnaryRepeatedEnumRequest")
	proto.RegisterType((*UnarySelfRequest)(nil), "api.UnarySelfRequest")
	proto.RegisterType((*Person)(nil), "api.Person")
	proto.RegisterType((*UnaryMapRequest)(nil), "api.UnaryMapRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.UnaryMapRequest.KvsEntry")
	proto.RegisterType((*UnaryMapMessageRequest)(nil), "api.UnaryMapMessageRequest")
	proto.RegisterMapType((map[string]*Name)(nil), "api.UnaryMapMessageRequest.KvsEntry")
	proto.RegisterType((*UnaryOneofRequest)(nil), "api.UnaryOneofRequest")
	proto.RegisterType((*UnaryEnumRequest)(nil), "api.UnaryEnumRequest")
	proto.RegisterType((*UnaryBytesRequest)(nil), "api.UnaryBytesRequest")
	proto.RegisterEnum("api.Gender", Gender_name, Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleClient interface {
	Unary(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryMessage(ctx context.Context, in *UnaryMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryRepeated(ctx context.Context, in *UnaryRepeatedRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryRepeatedMessage(ctx context.Context, in *UnaryRepeatedMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryRepeatedEnum(ctx context.Context, in *UnaryRepeatedEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnarySelf(ctx context.Context, in *UnarySelfRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryMap(ctx context.Context, in *UnaryMapRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryMapMessage(ctx context.Context, in *UnaryMapMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryOneof(ctx context.Context, in *UnaryOneofRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryEnum(ctx context.Context, in *UnaryEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryBytes(ctx context.Context, in *UnaryBytesRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_ClientStreamingClient, error)
	ServerStreaming(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (Example_ServerStreamingClient, error)
	BidiStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_BidiStreamingClient, error)
}

type exampleClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) Unary(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/Unary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryMessage(ctx context.Context, in *UnaryMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryRepeated(ctx context.Context, in *UnaryRepeatedRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryRepeated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryRepeatedMessage(ctx context.Context, in *UnaryRepeatedMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryRepeatedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryRepeatedEnum(ctx context.Context, in *UnaryRepeatedEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryRepeatedEnum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnarySelf(ctx context.Context, in *UnarySelfRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnarySelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryMap(ctx context.Context, in *UnaryMapRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryMapMessage(ctx context.Context, in *UnaryMapMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryMapMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryOneof(ctx context.Context, in *UnaryOneofRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryOneof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryEnum(ctx context.Context, in *UnaryEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryEnum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryBytes(ctx context.Context, in *UnaryBytesRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryBytes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_ClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Example_serviceDesc.Streams[0], "/api.Example/ClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleClientStreamingClient{stream}
	return x, nil
}

type Example_ClientStreamingClient interface {
	Send(*SimpleRequest) error
	CloseAndRecv() (*SimpleResponse, error)
	grpc.ClientStream
}

type exampleClientStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleClientStreamingClient) Send(m *SimpleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleClientStreamingClient) CloseAndRecv() (*SimpleResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SimpleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) ServerStreaming(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (Example_ServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Example_serviceDesc.Streams[1], "/api.Example/ServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Example_ServerStreamingClient interface {
	Recv() (*SimpleResponse, error)
	grpc.ClientStream
}

type exampleServerStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleServerStreamingClient) Recv() (*SimpleResponse, error) {
	m := new(SimpleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) BidiStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_BidiStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Example_serviceDesc.Streams[2], "/api.Example/BidiStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleBidiStreamingClient{stream}
	return x, nil
}

type Example_BidiStreamingClient interface {
	Send(*SimpleRequest) error
	Recv() (*SimpleResponse, error)
	grpc.ClientStream
}

type exampleBidiStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleBidiStreamingClient) Send(m *SimpleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleBidiStreamingClient) Recv() (*SimpleResponse, error) {
	m := new(SimpleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleServer is the server API for Example service.
type ExampleServer interface {
	Unary(context.Context, *SimpleRequest) (*SimpleResponse, error)
	UnaryMessage(context.Context, *UnaryMessageRequest) (*SimpleResponse, error)
	UnaryRepeated(context.Context, *UnaryRepeatedRequest) (*SimpleResponse, error)
	UnaryRepeatedMessage(context.Context, *UnaryRepeatedMessageRequest) (*SimpleResponse, error)
	UnaryRepeatedEnum(context.Context, *UnaryRepeatedEnumRequest) (*SimpleResponse, error)
	UnarySelf(context.Context, *UnarySelfRequest) (*SimpleResponse, error)
	UnaryMap(context.Context, *UnaryMapRequest) (*SimpleResponse, error)
	UnaryMapMessage(context.Context, *UnaryMapMessageRequest) (*SimpleResponse, error)
	UnaryOneof(context.Context, *UnaryOneofRequest) (*SimpleResponse, error)
	UnaryEnum(context.Context, *UnaryEnumRequest) (*SimpleResponse, error)
	UnaryBytes(context.Context, *UnaryBytesRequest) (*SimpleResponse, error)
	ClientStreaming(Example_ClientStreamingServer) error
	ServerStreaming(*SimpleRequest, Example_ServerStreamingServer) error
	BidiStreaming(Example_BidiStreamingServer) error
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/Unary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).Unary(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryMessage(ctx, req.(*UnaryMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryRepeated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRepeatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryRepeated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryRepeated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryRepeated(ctx, req.(*UnaryRepeatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryRepeatedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRepeatedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryRepeatedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryRepeatedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryRepeatedMessage(ctx, req.(*UnaryRepeatedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryRepeatedEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRepeatedEnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryRepeatedEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryRepeatedEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryRepeatedEnum(ctx, req.(*UnaryRepeatedEnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnarySelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnarySelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnarySelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnarySelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnarySelf(ctx, req.(*UnarySelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryMap(ctx, req.(*UnaryMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryMapMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMapMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryMapMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryMapMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryMapMessage(ctx, req.(*UnaryMapMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryOneof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryOneofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryOneof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryOneof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryOneof(ctx, req.(*UnaryOneofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryEnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryEnum(ctx, req.(*UnaryEnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryBytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryBytes(ctx, req.(*UnaryBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_ClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).ClientStreaming(&exampleClientStreamingServer{stream})
}

type Example_ClientStreamingServer interface {
	SendAndClose(*SimpleResponse) error
	Recv() (*SimpleRequest, error)
	grpc.ServerStream
}

type exampleClientStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleClientStreamingServer) SendAndClose(m *SimpleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleClientStreamingServer) Recv() (*SimpleRequest, error) {
	m := new(SimpleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Example_ServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SimpleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExampleServer).ServerStreaming(m, &exampleServerStreamingServer{stream})
}

type Example_ServerStreamingServer interface {
	Send(*SimpleResponse) error
	grpc.ServerStream
}

type exampleServerStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleServerStreamingServer) Send(m *SimpleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Example_BidiStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).BidiStreaming(&exampleBidiStreamingServer{stream})
}

type Example_BidiStreamingServer interface {
	Send(*SimpleResponse) error
	Recv() (*SimpleRequest, error)
	grpc.ServerStream
}

type exampleBidiStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleBidiStreamingServer) Send(m *SimpleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleBidiStreamingServer) Recv() (*SimpleRequest, error) {
	m := new(SimpleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _Example_Unary_Handler,
		},
		{
			MethodName: "UnaryMessage",
			Handler:    _Example_UnaryMessage_Handler,
		},
		{
			MethodName: "UnaryRepeated",
			Handler:    _Example_UnaryRepeated_Handler,
		},
		{
			MethodName: "UnaryRepeatedMessage",
			Handler:    _Example_UnaryRepeatedMessage_Handler,
		},
		{
			MethodName: "UnaryRepeatedEnum",
			Handler:    _Example_UnaryRepeatedEnum_Handler,
		},
		{
			MethodName: "UnarySelf",
			Handler:    _Example_UnarySelf_Handler,
		},
		{
			MethodName: "UnaryMap",
			Handler:    _Example_UnaryMap_Handler,
		},
		{
			MethodName: "UnaryMapMessage",
			Handler:    _Example_UnaryMapMessage_Handler,
		},
		{
			MethodName: "UnaryOneof",
			Handler:    _Example_UnaryOneof_Handler,
		},
		{
			MethodName: "UnaryEnum",
			Handler:    _Example_UnaryEnum_Handler,
		},
		{
			MethodName: "UnaryBytes",
			Handler:    _Example_UnaryBytes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreaming",
			Handler:       _Example_ClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreaming",
			Handler:       _Example_ServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStreaming",
			Handler:       _Example_BidiStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_6027c29d237ac4bb) }

var fileDescriptor_api_6027c29d237ac4bb = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x6d, 0x4f, 0xd3, 0x50,
	0x14, 0x5e, 0x29, 0x74, 0xeb, 0xe1, 0xd5, 0x0b, 0x92, 0x09, 0x99, 0x92, 0xa2, 0x91, 0xf0, 0x01,
	0x71, 0x1a, 0xf0, 0x2d, 0x1a, 0x66, 0xa6, 0x18, 0x83, 0x98, 0x2e, 0x7e, 0x36, 0x57, 0x77, 0x58,
	0x2a, 0xed, 0x6d, 0xed, 0xed, 0x16, 0xe7, 0x7f, 0xf0, 0x93, 0x7f, 0xd8, 0xdc, 0xdb, 0xde, 0xf5,
	0xb6, 0xa3, 0x80, 0x7c, 0xeb, 0x3d, 0xe7, 0x3c, 0xcf, 0x79, 0xce, 0xdb, 0x06, 0x36, 0x8d, 0xbc,
	0xbd, 0x28, 0x0e, 0x93, 0x90, 0x98, 0x34, 0xf2, 0x9c, 0x6d, 0x58, 0xec, 0x79, 0x41, 0xe4, 0xa3,
	0x8b, 0x3f, 0x87, 0xc8, 0x13, 0x42, 0x60, 0x96, 0xd1, 0x00, 0x9b, 0xc6, 0x96, 0xb1, 0x63, 0xbb,
	0xf2, 0xdb, 0xd9, 0x85, 0x25, 0x15, 0xc4, 0xa3, 0x90, 0x71, 0x24, 0x4d, 0xa8, 0x07, 0xc8, 0x39,
	0x1d, 0xa8, 0x40, 0xf5, 0x74, 0x3a, 0x30, 0xfb, 0x89, 0x06, 0x48, 0x5a, 0x00, 0x67, 0x5e, 0xcc,
	0x93, 0xaf, 0x1a, 0x9b, 0x2d, 0x2d, 0xd2, 0xbd, 0x09, 0xb6, 0x4f, 0x95, 0x77, 0x46, 0x7a, 0x1b,
	0xc2, 0x20, 0x9c, 0xce, 0x53, 0x58, 0xfd, 0xc2, 0x68, 0x3c, 0x3e, 0x49, 0x39, 0x95, 0xb4, 0x96,
	0x26, 0x6d, 0xbe, 0x6d, 0xef, 0x89, 0x52, 0x44, 0xfc, 0x44, 0xe5, 0x9a, 0x44, 0xb9, 0x18, 0x21,
	0x4d, 0xb0, 0x3f, 0x5d, 0x91, 0x39, 0xa9, 0xe8, 0x15, 0x6c, 0x16, 0x62, 0x2b, 0x33, 0x99, 0x17,
	0x65, 0x3a, 0x82, 0x66, 0x01, 0xdd, 0x65, 0xc3, 0x40, 0x41, 0x1f, 0x40, 0x7d, 0x80, 0xac, 0x8f,
	0x31, 0x97, 0xe8, 0xa5, 0xf6, 0xbc, 0x44, 0xbf, 0x97, 0x36, 0x57, 0xf9, 0x9c, 0xc7, 0xb0, 0x22,
	0x29, 0x7a, 0xe8, 0x9f, 0xe5, 0x59, 0xcd, 0x71, 0x38, 0xcc, 0xca, 0x4b, 0x61, 0x9f, 0x31, 0xe6,
	0x21, 0x73, 0x85, 0xdd, 0xf9, 0x01, 0x56, 0xfa, 0xbc, 0xa2, 0x11, 0x64, 0x03, 0x1a, 0xcc, 0xfb,
	0x7e, 0xae, 0xb7, 0x56, 0xbd, 0x85, 0xbc, 0xb3, 0xd8, 0x43, 0xd6, 0xe7, 0x4d, 0x53, 0x16, 0x57,
	0xc8, 0xa3, 0x7c, 0xce, 0x6f, 0x58, 0x4e, 0x27, 0x40, 0x23, 0xa5, 0xee, 0x11, 0x98, 0xe7, 0x23,
	0x9e, 0xb5, 0xa4, 0x25, 0x51, 0xa5, 0x90, 0xbd, 0x8f, 0x23, 0xde, 0x65, 0x49, 0x3c, 0x76, 0x45,
	0xe4, 0xc6, 0x01, 0x34, 0x94, 0x81, 0xac, 0x80, 0x79, 0x8e, 0xe3, 0x6c, 0x0d, 0xc4, 0x27, 0x59,
	0x83, 0xb9, 0x11, 0xf5, 0x87, 0x4a, 0x61, 0xfa, 0x78, 0x31, 0xf3, 0xcc, 0x70, 0xfe, 0x1a, 0xb0,
	0xae, 0x98, 0x4b, 0x73, 0x39, 0xd0, 0x35, 0xdc, 0x2f, 0x68, 0x28, 0x46, 0x96, 0xa4, 0x1c, 0x5d,
	0x2a, 0xe5, 0x9e, 0x2e, 0xa5, 0xd0, 0x4f, 0x4d, 0x95, 0x0b, 0xb7, 0x64, 0xaa, 0x53, 0x86, 0xa1,
	0x3e, 0xb1, 0x80, 0x0f, 0xa6, 0xe6, 0x70, 0x5c, 0x73, 0x85, 0x9d, 0xac, 0xc3, 0x5c, 0xe4, 0x53,
	0x8f, 0xa5, 0x35, 0x1e, 0xd7, 0xdc, 0xf4, 0xd9, 0xb1, 0xd2, 0xf9, 0x39, 0x87, 0xd9, 0x12, 0xe8,
	0xfb, 0xb3, 0x0d, 0x56, 0xba, 0x23, 0x92, 0xb5, 0xb4, 0x3e, 0x99, 0xcb, 0x79, 0x98, 0x89, 0xe9,
	0x8c, 0x13, 0xe4, 0xda, 0x9e, 0xf7, 0x69, 0x42, 0x25, 0x6e, 0xc1, 0x95, 0xdf, 0xbb, 0x77, 0xc1,
	0x4a, 0xa1, 0xa4, 0x01, 0xb3, 0x27, 0xd4, 0xc7, 0x95, 0x1a, 0x01, 0xb0, 0xde, 0x61, 0x20, 0xbe,
	0x8d, 0xf6, 0x9f, 0x3a, 0xd4, 0xbb, 0xbf, 0xa8, 0xb8, 0x6d, 0xd2, 0x86, 0x39, 0x49, 0x4a, 0x88,
	0x4c, 0x59, 0xf8, 0x59, 0xd8, 0x58, 0x2d, 0xd8, 0xd2, 0x5f, 0x01, 0xa7, 0x46, 0xde, 0xc0, 0x82,
	0x7e, 0xa9, 0xa4, 0xa9, 0xcd, 0xa4, 0x30, 0x90, 0x2a, 0x82, 0x23, 0x58, 0x2c, 0x9c, 0x12, 0xb9,
	0x93, 0x33, 0x94, 0x0e, 0xb9, 0x8a, 0xe2, 0xb4, 0x74, 0xf7, 0x4a, 0xcb, 0xd6, 0x34, 0xd3, 0xf5,
	0x34, 0x7d, 0xc8, 0xba, 0xab, 0x9f, 0x37, 0x69, 0x4d, 0xb3, 0x69, 0x63, 0xab, 0xa2, 0x7a, 0x0e,
	0xf6, 0xe4, 0xcc, 0xc9, 0xed, 0x9c, 0x42, 0x3b, 0xfb, 0x2a, 0xe8, 0x21, 0x34, 0xd4, 0x6e, 0x93,
	0xb5, 0x8b, 0xce, 0xad, 0x0a, 0xd8, 0xcd, 0x6f, 0x57, 0xb5, 0x62, 0xf3, 0x92, 0x53, 0xa9, 0xa2,
	0x79, 0x09, 0x90, 0x2f, 0x3c, 0x59, 0xcf, 0x19, 0xf4, 0x0b, 0xb8, 0xaa, 0x6e, 0xd9, 0x3a, 0xad,
	0xee, 0x6b, 0xb4, 0x4c, 0xe5, 0x95, 0xbb, 0xad, 0xe7, 0xd5, 0x97, 0xbd, 0x0a, 0xfc, 0x1a, 0x96,
	0xdf, 0xfa, 0x1e, 0xb2, 0xa4, 0x97, 0xc4, 0x48, 0x03, 0x8f, 0x0d, 0xfe, 0x63, 0x9b, 0x77, 0x0c,
	0x81, 0xef, 0x61, 0x3c, 0xc2, 0xf8, 0x26, 0xf8, 0x7d, 0x81, 0x5f, 0xec, 0x78, 0x7d, 0xef, 0x66,
	0xd9, 0xf7, 0x8d, 0x6f, 0x96, 0xfc, 0x6b, 0x7e, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x58, 0x3e,
	0x79, 0xf1, 0xa7, 0x07, 0x00, 0x00,
}
