// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_Male   Gender = 0
	Gender_Female Gender = 1
)

var Gender_name = map[int32]string{
	0: "Male",
	1: "Female",
}

var Gender_value = map[string]int32{
	"Male":   0,
	"Female": 1,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type SimpleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRequest) Reset()         { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()    {}
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *SimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRequest.Unmarshal(m, b)
}
func (m *SimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRequest.Marshal(b, m, deterministic)
}
func (m *SimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRequest.Merge(m, src)
}
func (m *SimpleRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleRequest.Size(m)
}
func (m *SimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRequest proto.InternalMessageInfo

func (m *SimpleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SimpleResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Name struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Name) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type UnaryMessageRequest struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryMessageRequest) Reset()         { *m = UnaryMessageRequest{} }
func (m *UnaryMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMessageRequest) ProtoMessage()    {}
func (*UnaryMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *UnaryMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMessageRequest.Unmarshal(m, b)
}
func (m *UnaryMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMessageRequest.Marshal(b, m, deterministic)
}
func (m *UnaryMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMessageRequest.Merge(m, src)
}
func (m *UnaryMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMessageRequest.Size(m)
}
func (m *UnaryMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMessageRequest proto.InternalMessageInfo

func (m *UnaryMessageRequest) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type UnaryRepeatedRequest struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryRepeatedRequest) Reset()         { *m = UnaryRepeatedRequest{} }
func (m *UnaryRepeatedRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryRepeatedRequest) ProtoMessage()    {}
func (*UnaryRepeatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *UnaryRepeatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryRepeatedRequest.Unmarshal(m, b)
}
func (m *UnaryRepeatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryRepeatedRequest.Marshal(b, m, deterministic)
}
func (m *UnaryRepeatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryRepeatedRequest.Merge(m, src)
}
func (m *UnaryRepeatedRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryRepeatedRequest.Size(m)
}
func (m *UnaryRepeatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryRepeatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryRepeatedRequest proto.InternalMessageInfo

func (m *UnaryRepeatedRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type UnaryRepeatedMessageRequest struct {
	Name                 []*Name  `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryRepeatedMessageRequest) Reset()         { *m = UnaryRepeatedMessageRequest{} }
func (m *UnaryRepeatedMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryRepeatedMessageRequest) ProtoMessage()    {}
func (*UnaryRepeatedMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *UnaryRepeatedMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryRepeatedMessageRequest.Unmarshal(m, b)
}
func (m *UnaryRepeatedMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryRepeatedMessageRequest.Marshal(b, m, deterministic)
}
func (m *UnaryRepeatedMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryRepeatedMessageRequest.Merge(m, src)
}
func (m *UnaryRepeatedMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryRepeatedMessageRequest.Size(m)
}
func (m *UnaryRepeatedMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryRepeatedMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryRepeatedMessageRequest proto.InternalMessageInfo

func (m *UnaryRepeatedMessageRequest) GetName() []*Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type UnaryRepeatedEnumRequest struct {
	Genders              []Gender `protobuf:"varint,1,rep,packed,name=genders,proto3,enum=api.Gender" json:"genders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryRepeatedEnumRequest) Reset()         { *m = UnaryRepeatedEnumRequest{} }
func (m *UnaryRepeatedEnumRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryRepeatedEnumRequest) ProtoMessage()    {}
func (*UnaryRepeatedEnumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *UnaryRepeatedEnumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryRepeatedEnumRequest.Unmarshal(m, b)
}
func (m *UnaryRepeatedEnumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryRepeatedEnumRequest.Marshal(b, m, deterministic)
}
func (m *UnaryRepeatedEnumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryRepeatedEnumRequest.Merge(m, src)
}
func (m *UnaryRepeatedEnumRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryRepeatedEnumRequest.Size(m)
}
func (m *UnaryRepeatedEnumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryRepeatedEnumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryRepeatedEnumRequest proto.InternalMessageInfo

func (m *UnaryRepeatedEnumRequest) GetGenders() []Gender {
	if m != nil {
		return m.Genders
	}
	return nil
}

type UnarySelfRequest struct {
	You                  *Person  `protobuf:"bytes,1,opt,name=you,proto3" json:"you,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnarySelfRequest) Reset()         { *m = UnarySelfRequest{} }
func (m *UnarySelfRequest) String() string { return proto.CompactTextString(m) }
func (*UnarySelfRequest) ProtoMessage()    {}
func (*UnarySelfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *UnarySelfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnarySelfRequest.Unmarshal(m, b)
}
func (m *UnarySelfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnarySelfRequest.Marshal(b, m, deterministic)
}
func (m *UnarySelfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnarySelfRequest.Merge(m, src)
}
func (m *UnarySelfRequest) XXX_Size() int {
	return xxx_messageInfo_UnarySelfRequest.Size(m)
}
func (m *UnarySelfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnarySelfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnarySelfRequest proto.InternalMessageInfo

func (m *UnarySelfRequest) GetYou() *Person {
	if m != nil {
		return m.You
	}
	return nil
}

type Person struct {
	Name                 *Name     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string    `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Friends              []*Person `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Person) GetFriends() []*Person {
	if m != nil {
		return m.Friends
	}
	return nil
}

type UnaryMapRequest struct {
	Kvs                  map[string]string `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UnaryMapRequest) Reset()         { *m = UnaryMapRequest{} }
func (m *UnaryMapRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMapRequest) ProtoMessage()    {}
func (*UnaryMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *UnaryMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMapRequest.Unmarshal(m, b)
}
func (m *UnaryMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMapRequest.Marshal(b, m, deterministic)
}
func (m *UnaryMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMapRequest.Merge(m, src)
}
func (m *UnaryMapRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMapRequest.Size(m)
}
func (m *UnaryMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMapRequest proto.InternalMessageInfo

func (m *UnaryMapRequest) GetKvs() map[string]string {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type UnaryMapMessageRequest struct {
	Kvs                  map[string]*Name `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UnaryMapMessageRequest) Reset()         { *m = UnaryMapMessageRequest{} }
func (m *UnaryMapMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryMapMessageRequest) ProtoMessage()    {}
func (*UnaryMapMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *UnaryMapMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryMapMessageRequest.Unmarshal(m, b)
}
func (m *UnaryMapMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryMapMessageRequest.Marshal(b, m, deterministic)
}
func (m *UnaryMapMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryMapMessageRequest.Merge(m, src)
}
func (m *UnaryMapMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryMapMessageRequest.Size(m)
}
func (m *UnaryMapMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryMapMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryMapMessageRequest proto.InternalMessageInfo

func (m *UnaryMapMessageRequest) GetKvs() map[string]*Name {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type UnaryOneofRequest struct {
	// Types that are valid to be assigned to Name:
	//	*UnaryOneofRequest_Msg
	//	*UnaryOneofRequest_Plain
	Name                 isUnaryOneofRequest_Name `protobuf_oneof:"name"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UnaryOneofRequest) Reset()         { *m = UnaryOneofRequest{} }
func (m *UnaryOneofRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryOneofRequest) ProtoMessage()    {}
func (*UnaryOneofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *UnaryOneofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryOneofRequest.Unmarshal(m, b)
}
func (m *UnaryOneofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryOneofRequest.Marshal(b, m, deterministic)
}
func (m *UnaryOneofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryOneofRequest.Merge(m, src)
}
func (m *UnaryOneofRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryOneofRequest.Size(m)
}
func (m *UnaryOneofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryOneofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryOneofRequest proto.InternalMessageInfo

type isUnaryOneofRequest_Name interface {
	isUnaryOneofRequest_Name()
}

type UnaryOneofRequest_Msg struct {
	Msg *Name `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

type UnaryOneofRequest_Plain struct {
	Plain string `protobuf:"bytes,2,opt,name=plain,proto3,oneof"`
}

func (*UnaryOneofRequest_Msg) isUnaryOneofRequest_Name() {}

func (*UnaryOneofRequest_Plain) isUnaryOneofRequest_Name() {}

func (m *UnaryOneofRequest) GetName() isUnaryOneofRequest_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UnaryOneofRequest) GetMsg() *Name {
	if x, ok := m.GetName().(*UnaryOneofRequest_Msg); ok {
		return x.Msg
	}
	return nil
}

func (m *UnaryOneofRequest) GetPlain() string {
	if x, ok := m.GetName().(*UnaryOneofRequest_Plain); ok {
		return x.Plain
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UnaryOneofRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UnaryOneofRequest_Msg)(nil),
		(*UnaryOneofRequest_Plain)(nil),
	}
}

type UnaryEnumRequest struct {
	Gender               Gender   `protobuf:"varint,1,opt,name=gender,proto3,enum=api.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryEnumRequest) Reset()         { *m = UnaryEnumRequest{} }
func (m *UnaryEnumRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryEnumRequest) ProtoMessage()    {}
func (*UnaryEnumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *UnaryEnumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryEnumRequest.Unmarshal(m, b)
}
func (m *UnaryEnumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryEnumRequest.Marshal(b, m, deterministic)
}
func (m *UnaryEnumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryEnumRequest.Merge(m, src)
}
func (m *UnaryEnumRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryEnumRequest.Size(m)
}
func (m *UnaryEnumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryEnumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryEnumRequest proto.InternalMessageInfo

func (m *UnaryEnumRequest) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_Male
}

type UnaryBytesRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryBytesRequest) Reset()         { *m = UnaryBytesRequest{} }
func (m *UnaryBytesRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryBytesRequest) ProtoMessage()    {}
func (*UnaryBytesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *UnaryBytesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryBytesRequest.Unmarshal(m, b)
}
func (m *UnaryBytesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryBytesRequest.Marshal(b, m, deterministic)
}
func (m *UnaryBytesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryBytesRequest.Merge(m, src)
}
func (m *UnaryBytesRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryBytesRequest.Size(m)
}
func (m *UnaryBytesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryBytesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryBytesRequest proto.InternalMessageInfo

func (m *UnaryBytesRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UnaryHeaderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryHeaderRequest) Reset()         { *m = UnaryHeaderRequest{} }
func (m *UnaryHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*UnaryHeaderRequest) ProtoMessage()    {}
func (*UnaryHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *UnaryHeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryHeaderRequest.Unmarshal(m, b)
}
func (m *UnaryHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryHeaderRequest.Marshal(b, m, deterministic)
}
func (m *UnaryHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryHeaderRequest.Merge(m, src)
}
func (m *UnaryHeaderRequest) XXX_Size() int {
	return xxx_messageInfo_UnaryHeaderRequest.Size(m)
}
func (m *UnaryHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryHeaderRequest proto.InternalMessageInfo

type MapResponse struct {
	Names                map[string]*Name `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MapResponse) Reset()         { *m = MapResponse{} }
func (m *MapResponse) String() string { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()    {}
func (*MapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *MapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResponse.Unmarshal(m, b)
}
func (m *MapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResponse.Marshal(b, m, deterministic)
}
func (m *MapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResponse.Merge(m, src)
}
func (m *MapResponse) XXX_Size() int {
	return xxx_messageInfo_MapResponse.Size(m)
}
func (m *MapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapResponse proto.InternalMessageInfo

func (m *MapResponse) GetNames() map[string]*Name {
	if m != nil {
		return m.Names
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Gender", Gender_name, Gender_value)
	proto.RegisterType((*SimpleRequest)(nil), "api.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "api.SimpleResponse")
	proto.RegisterType((*Name)(nil), "api.Name")
	proto.RegisterType((*UnaryMessageRequest)(nil), "api.UnaryMessageRequest")
	proto.RegisterType((*UnaryRepeatedRequest)(nil), "api.UnaryRepeatedRequest")
	proto.RegisterType((*UnaryRepeatedMessageRequest)(nil), "api.UnaryRepeatedMessageRequest")
	proto.RegisterType((*UnaryRepeatedEnumRequest)(nil), "api.UnaryRepeatedEnumRequest")
	proto.RegisterType((*UnarySelfRequest)(nil), "api.UnarySelfRequest")
	proto.RegisterType((*Person)(nil), "api.Person")
	proto.RegisterType((*UnaryMapRequest)(nil), "api.UnaryMapRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.UnaryMapRequest.KvsEntry")
	proto.RegisterType((*UnaryMapMessageRequest)(nil), "api.UnaryMapMessageRequest")
	proto.RegisterMapType((map[string]*Name)(nil), "api.UnaryMapMessageRequest.KvsEntry")
	proto.RegisterType((*UnaryOneofRequest)(nil), "api.UnaryOneofRequest")
	proto.RegisterType((*UnaryEnumRequest)(nil), "api.UnaryEnumRequest")
	proto.RegisterType((*UnaryBytesRequest)(nil), "api.UnaryBytesRequest")
	proto.RegisterType((*UnaryHeaderRequest)(nil), "api.UnaryHeaderRequest")
	proto.RegisterType((*MapResponse)(nil), "api.MapResponse")
	proto.RegisterMapType((map[string]*Name)(nil), "api.MapResponse.NamesEntry")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x6d, 0x53, 0xd3, 0x4e,
	0x10, 0x6f, 0x28, 0x2d, 0xcd, 0x96, 0x87, 0xfe, 0x8f, 0xfe, 0xb1, 0xb4, 0x53, 0x65, 0x0e, 0x1d,
	0x19, 0x5e, 0x20, 0x54, 0x07, 0x7c, 0x40, 0x1c, 0xca, 0x14, 0x71, 0x1c, 0xc4, 0x49, 0x75, 0x7c,
	0xe9, 0x9c, 0xf4, 0x28, 0x27, 0x79, 0x32, 0x49, 0x3b, 0xd6, 0xf7, 0x7e, 0x02, 0x3f, 0x9a, 0x5f,
	0xc8, 0xb9, 0x4b, 0x8e, 0x5c, 0x52, 0x02, 0x94, 0x77, 0xb9, 0xbd, 0xfd, 0xfd, 0xf6, 0xb7, 0x7b,
	0xbb, 0x3b, 0x01, 0x9d, 0xb8, 0x6c, 0xc3, 0xf5, 0x9c, 0xc0, 0x41, 0x79, 0xe2, 0x32, 0xbc, 0x0a,
	0x73, 0x5d, 0x66, 0xb9, 0x26, 0x35, 0xe8, 0x8f, 0x01, 0xf5, 0x03, 0x84, 0x60, 0xda, 0x26, 0x16,
	0xad, 0x69, 0x2b, 0xda, 0x9a, 0x6e, 0x88, 0x6f, 0xbc, 0x0e, 0xf3, 0xd2, 0xc9, 0x77, 0x1d, 0xdb,
	0xa7, 0xa8, 0x06, 0x33, 0x16, 0xf5, 0x7d, 0xd2, 0x97, 0x8e, 0xf2, 0x88, 0xdb, 0x30, 0xfd, 0x81,
	0x58, 0x14, 0x35, 0x01, 0xce, 0x98, 0xe7, 0x07, 0x5f, 0x15, 0x36, 0x5d, 0x58, 0xc4, 0x75, 0x03,
	0x74, 0x93, 0xc8, 0xdb, 0x29, 0x71, 0x5b, 0xe2, 0x06, 0x7e, 0x89, 0x9f, 0xc1, 0xe2, 0x67, 0x9b,
	0x78, 0xa3, 0xe3, 0x90, 0x53, 0x4a, 0x6b, 0x2a, 0xd2, 0xca, 0x2d, 0x7d, 0x83, 0xa7, 0xc2, 0xfd,
	0x2f, 0x55, 0x56, 0x05, 0xca, 0xa0, 0x2e, 0x25, 0x01, 0xed, 0x8d, 0x67, 0x94, 0xbf, 0xcc, 0x68,
	0x17, 0x1a, 0x09, 0xdf, 0xcc, 0x48, 0xf9, 0xab, 0x22, 0xed, 0x43, 0x2d, 0x81, 0xee, 0xd8, 0x03,
	0x4b, 0x42, 0x1f, 0xc1, 0x4c, 0x9f, 0xda, 0x3d, 0xea, 0xf9, 0x02, 0x3d, 0xdf, 0x2a, 0x0b, 0xf4,
	0x5b, 0x61, 0x33, 0xe4, 0x1d, 0xde, 0x82, 0x8a, 0xa0, 0xe8, 0x52, 0xf3, 0x2c, 0x8e, 0x9a, 0x1f,
	0x39, 0x83, 0x28, 0xbd, 0x10, 0xf6, 0x91, 0x7a, 0xbe, 0x63, 0x1b, 0xdc, 0x8e, 0xbf, 0x43, 0x31,
	0x3c, 0xde, 0x50, 0x08, 0x54, 0x87, 0x92, 0xcd, 0x4e, 0x2f, 0xd4, 0xd2, 0xca, 0x33, 0x97, 0x77,
	0xe6, 0x31, 0x6a, 0xf7, 0xfc, 0x5a, 0x5e, 0x24, 0x97, 0x88, 0x23, 0xef, 0xf0, 0x2f, 0x58, 0x08,
	0x5f, 0x80, 0xb8, 0x52, 0xdd, 0x13, 0xc8, 0x5f, 0x0c, 0xfd, 0xa8, 0x24, 0x4d, 0x81, 0x4a, 0xb9,
	0x6c, 0xbc, 0x1f, 0xfa, 0x1d, 0x3b, 0xf0, 0x46, 0x06, 0xf7, 0xac, 0x6f, 0x43, 0x49, 0x1a, 0x50,
	0x05, 0xf2, 0x17, 0x74, 0x14, 0xb5, 0x01, 0xff, 0x44, 0x55, 0x28, 0x0c, 0x89, 0x39, 0x90, 0x0a,
	0xc3, 0xc3, 0xcb, 0xa9, 0xe7, 0x1a, 0xfe, 0xa3, 0xc1, 0x92, 0x64, 0x4e, 0xbd, 0xcb, 0xb6, 0xaa,
	0xe1, 0x61, 0x42, 0x43, 0xd2, 0x33, 0x25, 0x65, 0xff, 0x5a, 0x29, 0x0f, 0x54, 0x29, 0x89, 0x7a,
	0x2a, 0xaa, 0x0c, 0xf8, 0x4f, 0x84, 0x3a, 0xb1, 0xa9, 0xa3, 0xbe, 0x98, 0xe5, 0xf7, 0xc7, 0xde,
	0xe1, 0x28, 0x67, 0x70, 0x3b, 0x5a, 0x82, 0x82, 0x6b, 0x12, 0x66, 0x87, 0x39, 0x1e, 0xe5, 0x8c,
	0xf0, 0xd8, 0x2e, 0x86, 0xef, 0x87, 0x77, 0xa2, 0x26, 0x50, 0xfb, 0x67, 0x15, 0x8a, 0x61, 0x8f,
	0x08, 0xd6, 0x54, 0xfb, 0x44, 0x57, 0xf8, 0x71, 0x24, 0xa6, 0x3d, 0x0a, 0xa8, 0xaf, 0xf4, 0x79,
	0x8f, 0x04, 0x44, 0xe0, 0x66, 0x0d, 0xf1, 0x8d, 0xab, 0x80, 0x84, 0xe3, 0x11, 0x25, 0x1c, 0x1f,
	0x7a, 0xe2, 0xdf, 0x1a, 0x94, 0xc5, 0xb3, 0x45, 0xd3, 0xbc, 0x05, 0x05, 0xae, 0x47, 0x16, 0xb6,
	0x21, 0x42, 0x2a, 0x0e, 0x22, 0xa9, 0xa8, 0x9e, 0xa1, 0x67, 0xfd, 0x00, 0x20, 0x36, 0xde, 0xb1,
	0xa6, 0xeb, 0xf7, 0xa1, 0x18, 0x26, 0x86, 0x4a, 0x30, 0x7d, 0x4c, 0x4c, 0x5a, 0xc9, 0x21, 0x80,
	0xe2, 0x21, 0xb5, 0xf8, 0xb7, 0xd6, 0xfa, 0xab, 0xc3, 0x4c, 0xe7, 0x27, 0xe1, 0x9b, 0x07, 0xb5,
	0xa0, 0x20, 0x32, 0x41, 0x48, 0x50, 0x25, 0x96, 0x56, 0x7d, 0x31, 0x61, 0x0b, 0x45, 0xe3, 0x1c,
	0x7a, 0x03, 0xb3, 0xea, 0x1e, 0x41, 0x35, 0xa5, 0x63, 0x12, 0xed, 0x92, 0x45, 0xb0, 0x0f, 0x73,
	0x89, 0x41, 0x47, 0xcb, 0x31, 0x43, 0x6a, 0xcd, 0x64, 0x51, 0x9c, 0xa4, 0xb6, 0x92, 0xd4, 0xb2,
	0x32, 0xce, 0x74, 0x3b, 0x4d, 0xef, 0xa2, 0xb7, 0x57, 0x97, 0x0f, 0x6a, 0x8e, 0xb3, 0x29, 0x4d,
	0x95, 0x45, 0xf5, 0x02, 0xf4, 0xcb, 0x25, 0x84, 0xfe, 0x8f, 0x29, 0x94, 0xa5, 0x94, 0x05, 0xdd,
	0x81, 0x92, 0x9c, 0x3c, 0x54, 0xbd, 0x6a, 0x19, 0x64, 0x01, 0x3b, 0xf1, 0x66, 0x91, 0xa5, 0x68,
	0x5c, 0x33, 0xc8, 0x59, 0x34, 0xaf, 0x00, 0xe2, 0x71, 0x44, 0x4b, 0x31, 0x83, 0x3a, 0x9f, 0x37,
	0xe5, 0x2d, 0x4a, 0xa7, 0xe4, 0x7d, 0x8b, 0x92, 0xc9, 0xb8, 0x62, 0xf2, 0xd4, 0xb8, 0xea, 0x28,
	0x66, 0x81, 0x5f, 0x43, 0x59, 0x99, 0x46, 0x74, 0x2f, 0x46, 0x27, 0xe6, 0x33, 0xbb, 0x9d, 0xd5,
	0x61, 0xfe, 0xe4, 0x11, 0x66, 0x52, 0x6f, 0x92, 0x79, 0x38, 0x84, 0xe5, 0x71, 0x82, 0x43, 0xc2,
	0xcc, 0x81, 0x47, 0x27, 0xe1, 0xd9, 0x8b, 0x7a, 0xfa, 0x0b, 0x0b, 0xce, 0xd5, 0x3d, 0x72, 0x15,
	0x45, 0x25, 0xbd, 0x4c, 0x70, 0x0e, 0xed, 0xca, 0xfa, 0x9f, 0x9e, 0x3b, 0x93, 0x0f, 0xe5, 0x1e,
	0x2c, 0x1c, 0x98, 0x8c, 0xda, 0x41, 0x37, 0xf0, 0x28, 0xb1, 0x98, 0xdd, 0x9f, 0x40, 0xfb, 0x9a,
	0xc6, 0xf1, 0x5d, 0xea, 0x0d, 0xa9, 0x77, 0x17, 0xfc, 0x26, 0xc7, 0xcf, 0xb5, 0x59, 0x8f, 0xdd,
	0x2d, 0xfa, 0xa6, 0xf6, 0xad, 0x28, 0x7e, 0xbf, 0x9e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x3c,
	0x29, 0x05, 0x44, 0x8b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleClient interface {
	Unary(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryMessage(ctx context.Context, in *UnaryMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryRepeated(ctx context.Context, in *UnaryRepeatedRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryRepeatedMessage(ctx context.Context, in *UnaryRepeatedMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryRepeatedEnum(ctx context.Context, in *UnaryRepeatedEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnarySelf(ctx context.Context, in *UnarySelfRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryMap(ctx context.Context, in *UnaryMapRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryMapMessage(ctx context.Context, in *UnaryMapMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryOneof(ctx context.Context, in *UnaryOneofRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryEnum(ctx context.Context, in *UnaryEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryBytes(ctx context.Context, in *UnaryBytesRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryHeader(ctx context.Context, in *UnaryHeaderRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryHeaderTrailer(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryHeaderTrailerFailure(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UnaryWithMapResponse(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*MapResponse, error)
	UnaryEcho(ctx context.Context, in *UnaryMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_ClientStreamingClient, error)
	ServerStreaming(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (Example_ServerStreamingClient, error)
	BidiStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_BidiStreamingClient, error)
}

type exampleClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleClient(cc grpc.ClientConnInterface) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) Unary(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/Unary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryMessage(ctx context.Context, in *UnaryMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryRepeated(ctx context.Context, in *UnaryRepeatedRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryRepeated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryRepeatedMessage(ctx context.Context, in *UnaryRepeatedMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryRepeatedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryRepeatedEnum(ctx context.Context, in *UnaryRepeatedEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryRepeatedEnum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnarySelf(ctx context.Context, in *UnarySelfRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnarySelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryMap(ctx context.Context, in *UnaryMapRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryMapMessage(ctx context.Context, in *UnaryMapMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryMapMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryOneof(ctx context.Context, in *UnaryOneofRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryOneof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryEnum(ctx context.Context, in *UnaryEnumRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryEnum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryBytes(ctx context.Context, in *UnaryBytesRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryBytes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryHeader(ctx context.Context, in *UnaryHeaderRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryHeaderTrailer(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryHeaderTrailer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryHeaderTrailerFailure(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryHeaderTrailerFailure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryWithMapResponse(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*MapResponse, error) {
	out := new(MapResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryWithMapResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UnaryEcho(ctx context.Context, in *UnaryMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/api.Example/UnaryEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_ClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Example_serviceDesc.Streams[0], "/api.Example/ClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleClientStreamingClient{stream}
	return x, nil
}

type Example_ClientStreamingClient interface {
	Send(*SimpleRequest) error
	CloseAndRecv() (*SimpleResponse, error)
	grpc.ClientStream
}

type exampleClientStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleClientStreamingClient) Send(m *SimpleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleClientStreamingClient) CloseAndRecv() (*SimpleResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SimpleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) ServerStreaming(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (Example_ServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Example_serviceDesc.Streams[1], "/api.Example/ServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Example_ServerStreamingClient interface {
	Recv() (*SimpleResponse, error)
	grpc.ClientStream
}

type exampleServerStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleServerStreamingClient) Recv() (*SimpleResponse, error) {
	m := new(SimpleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) BidiStreaming(ctx context.Context, opts ...grpc.CallOption) (Example_BidiStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Example_serviceDesc.Streams[2], "/api.Example/BidiStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleBidiStreamingClient{stream}
	return x, nil
}

type Example_BidiStreamingClient interface {
	Send(*SimpleRequest) error
	Recv() (*SimpleResponse, error)
	grpc.ClientStream
}

type exampleBidiStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleBidiStreamingClient) Send(m *SimpleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleBidiStreamingClient) Recv() (*SimpleResponse, error) {
	m := new(SimpleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleServer is the server API for Example service.
type ExampleServer interface {
	Unary(context.Context, *SimpleRequest) (*SimpleResponse, error)
	UnaryMessage(context.Context, *UnaryMessageRequest) (*SimpleResponse, error)
	UnaryRepeated(context.Context, *UnaryRepeatedRequest) (*SimpleResponse, error)
	UnaryRepeatedMessage(context.Context, *UnaryRepeatedMessageRequest) (*SimpleResponse, error)
	UnaryRepeatedEnum(context.Context, *UnaryRepeatedEnumRequest) (*SimpleResponse, error)
	UnarySelf(context.Context, *UnarySelfRequest) (*SimpleResponse, error)
	UnaryMap(context.Context, *UnaryMapRequest) (*SimpleResponse, error)
	UnaryMapMessage(context.Context, *UnaryMapMessageRequest) (*SimpleResponse, error)
	UnaryOneof(context.Context, *UnaryOneofRequest) (*SimpleResponse, error)
	UnaryEnum(context.Context, *UnaryEnumRequest) (*SimpleResponse, error)
	UnaryBytes(context.Context, *UnaryBytesRequest) (*SimpleResponse, error)
	UnaryHeader(context.Context, *UnaryHeaderRequest) (*SimpleResponse, error)
	UnaryHeaderTrailer(context.Context, *SimpleRequest) (*SimpleResponse, error)
	UnaryHeaderTrailerFailure(context.Context, *SimpleRequest) (*SimpleResponse, error)
	UnaryWithMapResponse(context.Context, *SimpleRequest) (*MapResponse, error)
	UnaryEcho(context.Context, *UnaryMessageRequest) (*SimpleResponse, error)
	ClientStreaming(Example_ClientStreamingServer) error
	ServerStreaming(*SimpleRequest, Example_ServerStreamingServer) error
	BidiStreaming(Example_BidiStreamingServer) error
}

// UnimplementedExampleServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServer struct {
}

func (*UnimplementedExampleServer) Unary(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unary not implemented")
}
func (*UnimplementedExampleServer) UnaryMessage(ctx context.Context, req *UnaryMessageRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryMessage not implemented")
}
func (*UnimplementedExampleServer) UnaryRepeated(ctx context.Context, req *UnaryRepeatedRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryRepeated not implemented")
}
func (*UnimplementedExampleServer) UnaryRepeatedMessage(ctx context.Context, req *UnaryRepeatedMessageRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryRepeatedMessage not implemented")
}
func (*UnimplementedExampleServer) UnaryRepeatedEnum(ctx context.Context, req *UnaryRepeatedEnumRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryRepeatedEnum not implemented")
}
func (*UnimplementedExampleServer) UnarySelf(ctx context.Context, req *UnarySelfRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnarySelf not implemented")
}
func (*UnimplementedExampleServer) UnaryMap(ctx context.Context, req *UnaryMapRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryMap not implemented")
}
func (*UnimplementedExampleServer) UnaryMapMessage(ctx context.Context, req *UnaryMapMessageRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryMapMessage not implemented")
}
func (*UnimplementedExampleServer) UnaryOneof(ctx context.Context, req *UnaryOneofRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryOneof not implemented")
}
func (*UnimplementedExampleServer) UnaryEnum(ctx context.Context, req *UnaryEnumRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryEnum not implemented")
}
func (*UnimplementedExampleServer) UnaryBytes(ctx context.Context, req *UnaryBytesRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryBytes not implemented")
}
func (*UnimplementedExampleServer) UnaryHeader(ctx context.Context, req *UnaryHeaderRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryHeader not implemented")
}
func (*UnimplementedExampleServer) UnaryHeaderTrailer(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryHeaderTrailer not implemented")
}
func (*UnimplementedExampleServer) UnaryHeaderTrailerFailure(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryHeaderTrailerFailure not implemented")
}
func (*UnimplementedExampleServer) UnaryWithMapResponse(ctx context.Context, req *SimpleRequest) (*MapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryWithMapResponse not implemented")
}
func (*UnimplementedExampleServer) UnaryEcho(ctx context.Context, req *UnaryMessageRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryEcho not implemented")
}
func (*UnimplementedExampleServer) ClientStreaming(srv Example_ClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreaming not implemented")
}
func (*UnimplementedExampleServer) ServerStreaming(req *SimpleRequest, srv Example_ServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreaming not implemented")
}
func (*UnimplementedExampleServer) BidiStreaming(srv Example_BidiStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method BidiStreaming not implemented")
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/Unary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).Unary(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryMessage(ctx, req.(*UnaryMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryRepeated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRepeatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryRepeated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryRepeated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryRepeated(ctx, req.(*UnaryRepeatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryRepeatedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRepeatedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryRepeatedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryRepeatedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryRepeatedMessage(ctx, req.(*UnaryRepeatedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryRepeatedEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRepeatedEnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryRepeatedEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryRepeatedEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryRepeatedEnum(ctx, req.(*UnaryRepeatedEnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnarySelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnarySelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnarySelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnarySelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnarySelf(ctx, req.(*UnarySelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryMap(ctx, req.(*UnaryMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryMapMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMapMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryMapMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryMapMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryMapMessage(ctx, req.(*UnaryMapMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryOneof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryOneofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryOneof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryOneof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryOneof(ctx, req.(*UnaryOneofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryEnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryEnum(ctx, req.(*UnaryEnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryBytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryBytes(ctx, req.(*UnaryBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryHeader(ctx, req.(*UnaryHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryHeaderTrailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryHeaderTrailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryHeaderTrailer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryHeaderTrailer(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryHeaderTrailerFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryHeaderTrailerFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryHeaderTrailerFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryHeaderTrailerFailure(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryWithMapResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryWithMapResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryWithMapResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryWithMapResponse(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UnaryEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Example/UnaryEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryEcho(ctx, req.(*UnaryMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_ClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).ClientStreaming(&exampleClientStreamingServer{stream})
}

type Example_ClientStreamingServer interface {
	SendAndClose(*SimpleResponse) error
	Recv() (*SimpleRequest, error)
	grpc.ServerStream
}

type exampleClientStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleClientStreamingServer) SendAndClose(m *SimpleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleClientStreamingServer) Recv() (*SimpleRequest, error) {
	m := new(SimpleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Example_ServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SimpleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExampleServer).ServerStreaming(m, &exampleServerStreamingServer{stream})
}

type Example_ServerStreamingServer interface {
	Send(*SimpleResponse) error
	grpc.ServerStream
}

type exampleServerStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleServerStreamingServer) Send(m *SimpleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Example_BidiStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).BidiStreaming(&exampleBidiStreamingServer{stream})
}

type Example_BidiStreamingServer interface {
	Send(*SimpleResponse) error
	Recv() (*SimpleRequest, error)
	grpc.ServerStream
}

type exampleBidiStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleBidiStreamingServer) Send(m *SimpleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleBidiStreamingServer) Recv() (*SimpleRequest, error) {
	m := new(SimpleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _Example_Unary_Handler,
		},
		{
			MethodName: "UnaryMessage",
			Handler:    _Example_UnaryMessage_Handler,
		},
		{
			MethodName: "UnaryRepeated",
			Handler:    _Example_UnaryRepeated_Handler,
		},
		{
			MethodName: "UnaryRepeatedMessage",
			Handler:    _Example_UnaryRepeatedMessage_Handler,
		},
		{
			MethodName: "UnaryRepeatedEnum",
			Handler:    _Example_UnaryRepeatedEnum_Handler,
		},
		{
			MethodName: "UnarySelf",
			Handler:    _Example_UnarySelf_Handler,
		},
		{
			MethodName: "UnaryMap",
			Handler:    _Example_UnaryMap_Handler,
		},
		{
			MethodName: "UnaryMapMessage",
			Handler:    _Example_UnaryMapMessage_Handler,
		},
		{
			MethodName: "UnaryOneof",
			Handler:    _Example_UnaryOneof_Handler,
		},
		{
			MethodName: "UnaryEnum",
			Handler:    _Example_UnaryEnum_Handler,
		},
		{
			MethodName: "UnaryBytes",
			Handler:    _Example_UnaryBytes_Handler,
		},
		{
			MethodName: "UnaryHeader",
			Handler:    _Example_UnaryHeader_Handler,
		},
		{
			MethodName: "UnaryHeaderTrailer",
			Handler:    _Example_UnaryHeaderTrailer_Handler,
		},
		{
			MethodName: "UnaryHeaderTrailerFailure",
			Handler:    _Example_UnaryHeaderTrailerFailure_Handler,
		},
		{
			MethodName: "UnaryWithMapResponse",
			Handler:    _Example_UnaryWithMapResponse_Handler,
		},
		{
			MethodName: "UnaryEcho",
			Handler:    _Example_UnaryEcho_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreaming",
			Handler:       _Example_ClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreaming",
			Handler:       _Example_ServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStreaming",
			Handler:       _Example_BidiStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
